# Generated by Django 4.2.7 on 2025-07-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialreceipt',
            name='mode_of_payment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='officialreceipt',
            name='payment_channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
