# Generated by Django 4.2.7 on 2025-07-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_alter_officialreceipt_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialreceipt',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
